# Generated by Django 5.0.3 on 2024-04-04 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework2app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.CharField(default=datetime.date(2024, 4, 4), max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_registration',
            field=models.CharField(default=datetime.date(2024, 4, 4), max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.CharField(default=datetime.date(2024, 4, 4), max_length=12),
        ),
    ]
